version: '3.8'

networks:
  app1-network:

volumes:
  mysql8_data_volume:


services:
  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php81-service
      - mysql8-service
    links:
      - "php81-service:php-fpm"
    networks:
      - app1-network

  # php
  php81-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php81-container
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/project
    networks:
      - app1-network

  # mysql
  mysql8-service:
    image: mysql:8.0
    container_name: mysql8-container
    ports:
      - "3306:3306"
    volumes:
      - mysql8_data_volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
    networks:
      - app1-network
