version: '3.8'

networks:
  app1-network:

volumes:
  mysql_data_volume:


services:

  # nginx
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php74-service
      - mysql5-service
    networks:
      - app1-network

  # php
  php74-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php74-container
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/project
    networks:
      - app1-network

  # mysql
  mysql5-service:
    image: mysql:5.6.44
    container_name: mysql5-container
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_volume:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always # always restart unless stopped manually
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: secret
    networks:
      - app1-network

  # node
#  node-service:
#    image: node:latest
#    container_name: node-container
#    volumes:
#      - ./:/var/www/project
#    working_dir: /var/www/project
#    networks:
#      - app1-network
