version: '3.8'

services:
  # php
  php81-service:
    build:
      context: .
      dockerfile: ./docker/php/DockerfileDev
    volumes:
      - ./docker/php/config/100-xdebug.ini:/usr/local/etc/php/conf.d/100-xdebug.ini